# Generated by Django 4.0.5 on 2022-07-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labels',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='author_id',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='labels',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
