# Generated by Django 4.0.5 on 2022-07-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_rename_author_id_labels_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='name',
            field=models.CharField(max_length=20, unique=False),
        ),
    ]
